### ISSUE TITLE
Crash Bench Dashboard / perhaps better DNS-Call Github.com

### ISSUE THREAD

**Issue by floriandd2ba** [winbench/bench#132]
Hi,

i get a Error after some time the Dashboard is running.
(And in the left lower Corner of the Dashboard the circle ist alwas running.)
Perhaps is a dns-call "github.com" better than using a IP.

**Error:**
************** Ausnahmetext **************
System.Net.Sockets.SocketException (0x80004005): Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat 192.30.253.112:443
   bei System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)

I think, its a Problem wit my Proxy, because the https-certifacte don't match the IP:

Zertifikatsfehler (ssl_domain_invalid)
Your request contacted a host which presented a certificate with a Common Name that did not match the domain requested. The request was made to 192.30.253.112 but the Common Name in the certificate is for github.com.
This is typically caused by a Web Site presenting an incorrect or invalid certificate, but could be because of a configuration error.

Thank you
Florian

**Comment by mastersign** [comment]
Hi Florian,
Bench does not use hardcoded IP addresses. I think you may be right, with your assumption about the proxy. Is the error permanent or does it occur only from time to time?
Greetings, Tobias

**Comment by mastersign** [comment]
And to clarify, are you talking about the version check symbol in the right end of the status bar? I will check if the version check is done properly with respect to the proxy settings. I might have made a mistake there.

To avoid the error in the meantime, you can set the config property `AutoUpdateCheck`to `false` in your `config/config.md` (<https://winbench.org/ref/config/#AutoUpdateCheck>).

Dashboard &rarr; Setup Dialog &rarr; Menu _Edit Configuration_ &rarr; _User Configuration_

**Comment by mastersign** [comment]
Try to upgrade to version 0.20.2 and leave a comment whether it fixes the issue or not.

**Comment by floriandd2ba** [comment]
Hi,
thanks for your fast response.
I will try the new version tomorrow and then send feedback.

**Comment by floriandd2ba** [comment]
Sorry, i can't try this today.
My USB-Stick crashed and no time at work.

**Comment by floriandd2ba** [comment]
Hi, sorry for my late response.
With version 0.20.2 the Dashboard don`t crash.
The version check symbol spin a time and then stop.
This is okay, the proxy of my work enviroment ist very restrictive (no download from executable files and scripts).

So for me the issue is fixed.
THX
